=== officialanant24-1/accessibility-app/testng-1.0.dtd
<!ELEMENT suite (test+)>
<!ATTLIST suite
  name               CDATA     #REQUIRED
  parallel           (tests | methods | classes | instances | none) "none"
  thread-count       CDATA     "5"
>

<!ELEMENT test (parameter*, classes)>
<!ATTLIST test
  name               CDATA     #REQUIRED
  parallel           (tests | methods | classes | instances | none) "none"
  thread-count       CDATA     "5"
>

<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
  name  CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT classes (class+)>
<!ELEMENT class (methods?)>
<!ATTLIST class
  name CDATA #REQUIRED
>

<!ELEMENT methods (include*, exclude*)>
<!ELEMENT include EMPTY>
<!ATTLIST include
  name CDATA #REQUIRED
>

<!ELEMENT exclude EMPTY>
<!ATTLIST exclude
  name CDATA #REQUIRED
>

=== officialanant24-1/accessibility-app/testng.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "testng-1.0.dtd">
<suite name="Accessibility Tests">
    <test name="Test on Chrome">
        <parameter name="browser" value="chrome"/>
        <classes>
            <class name="accessibility.wcag.WcagTest"/>
        </classes>
    </test>

    <test name="Test on Firefox">
        <parameter name="browser" value="firefox"/>
        <classes>
            <class name="accessibility.wcag.WcagTest">
            </class>
        </classes>
    </test>
</suite>
